In [4]:
import numpy as np


In [ ]:
## creating numpy array

In [5]:
my_list=[1,2,3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
x=np.array(my_list)

In [8]:
type(x)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,10,21) ##linearly sacing numbers from 0 to 10

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(1) ##any random number bw 0 and 1

array([0.78893114])

In [15]:
np.random.rand(5,4) ##any random number bw 0 and 1 w uniform distribution 
##ie same odds of being picked

array([[0.46353231, 0.79365589, 0.81641677, 0.59242182],
       [0.56599829, 0.18730617, 0.06821171, 0.61779435],
       [0.12819032, 0.05600551, 0.80338079, 0.12628225],
       [0.63293891, 0.12105916, 0.61665059, 0.43996533],
       [0.73945614, 0.29976503, 0.88107363, 0.21047219]])

In [16]:
np.random.randn(5) ##the closer to 0, the more probability of getting picked up

array([-0.59816165, -0.44680302,  1.29196388,  0.99398988,  0.03842081])

In [18]:
np.random.randint(1,60,5) ##get 5 random numbers from 1 to 59

array([30, 22, 30, 16, 34])

In [19]:
arr= np.arange(25)
ranarr= np.random.randint(0,50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr

array([45, 21, 20, 10,  6, 11,  5, 49, 22, 21])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.shape ##indiccating its a one dimensional array

(25,)

In [24]:
arr.reshape(5,5).shape ## 5 rows and 5 columns

(5, 5)

In [25]:
arr.reshape(25,).shape

(25,)

In [26]:
arr.dtype

dtype('int32')

In [28]:
ranarr.max()

49

In [29]:
ranarr.argmax() ##get the index of the max vol

7

### numpy operations

In [30]:
arr=np.arange(0,10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
1/arr ##check out the infinity error

<ipython-input-35-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [36]:
arr **3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [37]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### np indexing

In [39]:
arr=np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr=np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr=arr[0:6]
slice_of_arr
slice_of_arr[:]=90
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [47]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [48]:
arr_copy=arr.copy()
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [49]:
arr_copy[:]=200
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [50]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [51]:
## mat[row,col]
## mat[row][col]

In [52]:
mat=np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
mat[0] ##to get my first row

array([ 5, 10, 15])

In [54]:
mat[1][1]

25

In [55]:
mat[1,1]

25

In [56]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

### conditional selection

In [59]:
arr=np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### exercise

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(1)

array([0.96508516])

In [9]:
np.random.randn(25)

array([ 1.48002311, -1.08590973,  0.23266697,  1.100454  ,  1.74590197,
        1.24508076,  1.72489782, -0.43817541, -0.34693922,  0.18892588,
       -1.11357797, -0.32433245,  0.97533066, -0.50547537, -1.57807934,
        0.58946614, -0.52609224,  0.95709799, -0.36272251, -0.58632322,
        1.47036053,  2.03851795, -0.78892866,  1.85929061,  0.82872207])

In [10]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
mat=np.arange(1,26).reshape(5,5)

In [12]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[3,4]

20

In [16]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [20]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat.sum()

325

In [22]:
mat.std() ##standard deviation

7.211102550927978

In [23]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
mat.sum(axis=0) ##gonna sub along the rows 1+6+11+16+21

array([55, 60, 65, 70, 75])

In [25]:
np.random.seed(101) ##to get the same random number as that of the teacher

In [28]:
np.random.rand(1)

array([0.02847423])